# Generated by Django - Migration for MentorshipRequest model

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),  # Adjust this based on your accounts app migrations
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_role', models.CharField(max_length=255)),
                ('field', models.CharField(choices=[('software_engineering', 'Software Engineering'), ('data_science', 'Data Science'), ('machine_learning', 'Machine Learning'), ('product_management', 'Product Management'), ('ui_ux_design', 'UI/UX Design'), ('cybersecurity', 'Cybersecurity'), ('devops', 'DevOps'), ('mobile_development', 'Mobile Development'), ('web_development', 'Web Development'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('consulting', 'Consulting'), ('other', 'Other')], max_length=30)),
                ('topics', models.CharField(help_text='Comma-separated topics/skills needed', max_length=500)),
                ('experience_level', models.CharField(choices=[('student', 'Student'), ('entry_level', 'Entry Level (0-1 years)'), ('junior', 'Junior (1-3 years)'), ('mid_level', 'Mid Level (3-5 years)'), ('senior', 'Senior (5+ years)')], max_length=20)),
                ('preferred_time', models.CharField(blank=True, choices=[('morning', 'Morning (6 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 6 PM)'), ('evening', 'Evening (6 PM - 11 PM)'), ('weekend', 'Weekends'), ('flexible', 'Flexible')], max_length=20, null=True)),
                ('session_frequency', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('as_needed', 'As needed')], max_length=20, null=True)),
                ('budget', models.CharField(choices=[('free', 'Free/Volunteer'), ('under_500', 'Under $500'), ('500_1000', '$500 - $1000'), ('1000_2000', '$1000 - $2000'), ('2000_3000', '$2000 - $3000'), ('3000_5000', '$3000 - $5000'), ('above_5000', 'Above $5000')], max_length=20)),
                ('duration', models.CharField(blank=True, choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('ongoing', 'Ongoing')], max_length=20, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matched', 'Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests', to='accounts.user')),
            ],
            options={
                'db_table': 'mentorship_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mentorshiprequest',
            index=models.Index(fields=['field'], name='mentorship__field_9f4c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshiprequest',
            index=models.Index(fields=['budget'], name='mentorship__budget_4f1e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshiprequest',
            index=models.Index(fields=['experience_level'], name='mentorship__experie_8a2f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshiprequest',
            index=models.Index(fields=['status'], name='mentorship__status_1e4b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshiprequest',
            index=models.Index(fields=['created_at'], name='mentorship__created_7c5e2a_idx'),
        ),
    ]
